import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head';
import Layout from '@/component/templates/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <>
      <html lang="ja">
        <Head>
          <title>{metadata.title + ""}</title>
          <meta name="description" content={metadata.description + ""} />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet" />
        </Head>
        <body>
          <Layout>{children}</Layout>
        </body>
      </html>
    </>
  );
}