import Layout from '@/component/templates/Layout'
import './globals.css'
import type { Metadata } from 'next'
import Header from '@/component/templates/Header';
import Footer from '@/component/templates/Footer';
import { Box } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html>
      <head />
      <body>
        <Box>
          <Header />
          {children}
          <Footer />
        </Box>
      </body>
    </html>
  );
}