import './globals.css'
import type { Metadata } from 'next'
import Layout from '@/component/templates/Layout';

import {Noto_Sans_JP} from "next/font/google";
import React from "react";

const font = Noto_Sans_JP({
  weight: '600',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <>
      <html lang="ja">
        <body>
          <Layout>{children}</Layout>
        </body>
      </html>
    </>
  );
}